import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "node:fs";
import path from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

/* ----------------------------------------------------------------
 *  CLI parsing
 *
 *  node esbuild.config.mjs                  → dev watch (pro)
 *  node esbuild.config.mjs free             → dev watch (free)
 *  node esbuild.config.mjs production       → build both editions
 *  node esbuild.config.mjs production free  → build free only
 *  node esbuild.config.mjs production pro   → build pro only
 * ---------------------------------------------------------------- */

const args = process.argv.slice(2);
const prod = args.includes("production");
const requestedEdition = args.find((a) => a === "free" || a === "pro");

/* ----------------------------------------------------------------
 *  Shared externals
 * ---------------------------------------------------------------- */

const EXTERNALS = [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
];

/* ----------------------------------------------------------------
 *  Build option factory
 *
 *  `edition` is "free" or "pro".
 *  `isProd`  controls minification, sourcemaps, and output path.
 * ---------------------------------------------------------------- */

function buildOptions(edition, isProd) {
    const outdir = isProd ? `dist-${edition}` : ".";
    return {
        banner: { js: banner },
        entryPoints: ["src/main.ts"],
        bundle: true,
        external: EXTERNALS,
        format: "cjs",
        target: "es2018",
        logLevel: "info",
        treeShaking: true,
        outfile: path.join(outdir, "main.js"),
        sourcemap: isProd ? false : "inline",
        minify: isProd,
        define: {
            // esbuild replaces every `IS_PRO` token with a literal
            // boolean.  Dead-code elimination then strips the
            // unreachable branches, and tree-shaking removes the
            // now-unused imports (e.g. view.ts in the free build).
            IS_PRO: edition === "pro" ? "true" : "false",
        },
    };
}

/* ----------------------------------------------------------------
 *  Copy companion files into the dist folder
 *
 *  Manifest priority:
 *    manifest-<edition>.json  →  manifest.json  (fallback)
 *
 *  This lets you maintain a single manifest.json for the common
 *  case, or per-edition overrides (different id / name / description)
 *  when you need them.
 * ---------------------------------------------------------------- */

function copyAssets(edition) {
    const outdir = `dist-${edition}`;
    fs.mkdirSync(outdir, { recursive: true });

    // styles.css
    if (fs.existsSync("styles.css")) {
        fs.copyFileSync("styles.css", path.join(outdir, "styles.css"));
    }

    // manifest.json (edition-specific takes precedence)
    const editionManifest = `manifest-${edition}.json`;
    const manifestSrc = fs.existsSync(editionManifest)
        ? editionManifest
        : "manifest.json";
    fs.copyFileSync(manifestSrc, path.join(outdir, "manifest.json"));
}

/* ----------------------------------------------------------------
 *  Main
 * ---------------------------------------------------------------- */

if (prod) {
    // Production: build one or both editions
    const editions = requestedEdition ? [requestedEdition] : ["free", "pro"];

    for (const edition of editions) {
        console.log(`\n📦 Building ${edition} edition...`);
        const options = buildOptions(edition, true);
        await esbuild.build(options);
        copyAssets(edition);
        console.log(`✅ ${edition} → dist-${edition}/`);
    }

    process.exit(0);
} else {
    // Development: watch mode, output to repo root for Obsidian hot-reload
    const devEdition = requestedEdition ?? "pro";
    console.log(`👀 Watching (${devEdition} edition)...`);
    const context = await esbuild.context(buildOptions(devEdition, false));
    await context.watch();
}